server:
  port: 8084

spring:
  # DB 서버 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/2c2j
    username: root
    password: 1234

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create # create: 테이블 삭제 후 새로 생성, update: 현재 테이블 업데이트
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  # 구글 로그인 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 284545336598-ujugr5b3hllt276gsievui3es4an0psb.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

logging:
  level:
    org.hibernate.SQL: debug
