server:
  port: 8084

spring:
  # DB 연동 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/2c2j
    username: root
    password: 1234

    # spring data jpa 설정
    jpa:
      database-platform: org.hibernate.dialect.MariaDB106Dialect
      open-in-view: false
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate.format_sql: true
        dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  logging:
    level:
      org.hibernate.SQL: debug